/** Shared Tailwind CDN config — single source for design tokens */
tailwind.config = {
    theme: {
        extend: {
            colors: {
                'primary-container': '#1a1f2c',
                'outline-variant': '#c6c6cc',
                'tertiary-fixed': '#d7e4f3',
                'on-error-container': '#93000a',
                'on-secondary-container': '#fefcff',
                'on-tertiary-fixed': '#111d28',
                'inverse-on-surface': '#eff1f3',
                'surface-container-lowest': '#ffffff',
                'on-primary': '#ffffff',
                'on-primary-fixed-variant': '#424655',
                'tertiary-container': '#14202b',
                'secondary-container': '#2170e4',
                'on-secondary': '#ffffff',
                'secondary-fixed-dim': '#adc6ff',
                'outline': '#76777c',
                'on-primary-container': '#828697',
                'on-tertiary': '#ffffff',
                'on-secondary-fixed': '#001a42',
                'on-tertiary-fixed-variant': '#3c4854',
                'background': '#f7f9fb',
                'surface-container-highest': '#e0e3e5',
                'on-primary-fixed': '#161b28',
                'on-secondary-fixed-variant': '#004395',
                'surface-container-low': '#f2f4f6',
                'error-container': '#ffdad6',
                'primary': '#030612',
                'primary-fixed-dim': '#c2c6d8',
                'surface-container': '#eceef0',
                'surface-dim': '#d8dadc',
                'surface': '#f7f9fb',
                'on-error': '#ffffff',
                'secondary-fixed': '#d8e2ff',
                'primary-fixed': '#dee2f4',
                'inverse-primary': '#c2c6d8',
                'success-emerald': '#10b981',
                'surface-variant': '#e0e3e5',
                'border-subtle': 'rgba(26, 31, 44, 0.08)',
                'on-background': '#191c1e',
                'tertiary': '#000711',
                'surface-container-high': '#e6e8ea',
                'secondary': '#0058be',
                'on-tertiary-container': '#7c8896',
                'on-surface-variant': '#45464c',
                'error': '#ba1a1a',
                'surface-bright': '#f7f9fb',
                'inverse-surface': '#2d3133',
                'surface-glass': 'rgba(248, 250, 252, 0.8)',
                'surface-tint': '#595e6d',
                'tertiary-fixed-dim': '#bbc8d7',
                'on-surface': '#191c1e'
            },
            spacing: {
                'margin-desktop': '64px',
                'stack-lg': '32px',
                'container-max': '1280px',
                'margin-mobile': '24px',
                'stack-md': '16px',
                'stack-sm': '8px',
                'gutter': '24px'
            },
            fontFamily: {
                'display-lg-mobile': ['Sora', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'headline-md': ['Sora', 'sans-serif'],
                'headline-lg': ['Sora', 'sans-serif'],
                'headline-lg-mobile': ['Sora', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'display-lg': ['Sora', 'sans-serif']
            },
            fontSize: {
                'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }]
            }
        }
    }
};
